# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhW59yOM7FjZ1XjTh12b1Lhy21Qa4isj
"""

import streamlit as st

# Page configuration
st.set_page_config(
    page_title="BMI Calculator",
    page_icon="⚖️",
    layout="centered"
)



# Title
st.title("⚖️ BMI Calculator")



st.write(
    """
    Calculate your Body Mass Index (BMI)
    by entering your weight and height.
    """
)



# User Inputs
weight = st.number_input(
    "Enter Weight (kg)",
    min_value=1.0,
    max_value=300.0,
    value=70.0
)



h
eight = st.number_input(
    "Enter Height (m)",
    min_value=0.5,
    max_value=3.0,
    value=1.75
)



if st.button("Calculate BMI"):



    bmi = weight / (height ** 2)



    st.subheader(f"Your BMI: {bmi:.2f}")



    if bmi < 18.5:
        st.warning("Underweight")
    elif bmi < 25:
        st.success("Normal Weight")
    elif bmi < 30:
        st.warning("Overweight")
    else:
        st.error("Obese")



    st.progress(min(int(bmi), 100))


st.markdown("---")
st.caption("Created using Streamlit")